[project]
name = "alternative-embedding-pooling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mteb>=1.38.28",
    "sentence-transformers>=4.1.0",
]
